version: '3'

volumes:
  pg_data:
  static:

services:

  db:
    build: ./postgres/
    container_name: db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 30

  backend:
    build: ./django-prj/
    container_name: backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static

  nginx:
    build: ./nginx/
    container_name: nginx
    env_file: .env
    ports:
      - 8010:80
    volumes:
      - static:/static
    depends_on:
      - backend
