# Generated by Django 5.0.1 on 2024-02-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_questionsession_surveysession"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="session",
            field=models.CharField(default=123, max_length=500, verbose_name="Сессия"),
            preserve_default=False,
        ),
    ]
