# Generated by Django 5.0.1 on 2024-02-03 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_answer_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variant",
            old_name="question",
            new_name="parent_question",
        ),
        migrations.AddField(
            model_name="variant",
            name="next_question",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.question",
            ),
        ),
    ]
