# Generated by Django 5.0.1 on 2024-02-03 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_question_variant_parent_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="next_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.question",
            ),
        ),
    ]
