# Generated by Django 5.0.1 on 2024-02-04 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_variant_next_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="variant",
            old_name="parent_question",
            new_name="question",
        ),
    ]
