# Generated by Django 5.0.1 on 2024-02-08 23:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_rename_parent_question_variant_question"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questionsession",
            unique_together={("question", "session")},
        ),
    ]
